version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: study-link-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=study_link_db
    volumes:
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume: